services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=/api
    volumes:
      - ./backend/db:/usr/src/app/db
    networks:
      - myNetwork

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SUBDOMAIN=rio_ferdinan
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge